In [1]:

from dask_jobqueue import SLURMCluster # pip 
from dask.distributed import Client, progress 
import dask


import matplotlib as mpl
# Define Agg as Backend for matplotlib when no X server is running
mpl.use('Agg')
import socket
import os
import importlib 

In [2]:

def squeue_user(username = "$USER"):
    _squeue_user = os.system("squeue --user="+str(username))
    return _squeue_user 

with os.popen("pwd ") as f:
    _pwd = f.readline()

In [3]:
cluster = SLURMCluster(
    name='dask-cluster', 
    cores=256,    
    memory="500 GB", 
    project="bb1153",
    queue= "compute", 
    #interface='ib0',
    walltime='04:30:50',
)
client = Client(cluster)
print(cluster.job_script())

/home/b/b382267/mambaforge/envs/aqua/lib/python3.10/site-packages/dask_jobqueue/slurm.py:49: FutureWarning: project has been renamed to account as this kwarg was used wit -A option. You are still using it (please also check config files). If you did not set account yet, project will be respected for now, but it will be removed in a future release. If you already set account, project is ignored and you can remove it.
  warnings.warn(warn, FutureWarning)


#!/usr/bin/env bash

#SBATCH -J dask-worker
#SBATCH -p compute
#SBATCH -A bb1153
#SBATCH -n 1
#SBATCH --cpus-per-task=256
#SBATCH --mem=466G
#SBATCH -t 04:30:50

/home/b/b382267/mambaforge/envs/aqua/bin/python -m distributed.cli.dask_worker tcp://136.172.124.7:35999 --nthreads 16 --nworkers 16 --memory-limit 29.10GiB --name dummy-name --nanny --death-timeout 60



/home/b/b382267/mambaforge/envs/aqua/lib/python3.10/site-packages/distributed/node.py:182: UserWarning: Port 8787 is already in use.
Perhaps you already have a cluster running?
Hosting the HTTP server on port 36727 instead
  warnings.warn(
/home/b/b382267/mambaforge/envs/aqua/lib/python3.10/site-packages/dask_jobqueue/slurm.py:49: FutureWarning: project has been renamed to account as this kwarg was used wit -A option. You are still using it (please also check config files). If you did not set account yet, project will be respected for now, but it will be removed in a future release. If you already set account, project is ignored and you can remove it.
  warnings.warn(warn, FutureWarning)


In [4]:
cluster.scale(jobs=1)

In [10]:
squeue_user()

             JOBID PARTITION     NAME     USER ST       TIME  NODES NODELIST(REASON)
           4268030   compute dask-wor  b382267  R    1:53:45      1 l40170
           4268031   compute dask-wor  b382267  R    1:53:45      1 l40252


0

In [7]:
os.system("scancel  4265508") 

0

In [11]:
while True:
    try:
        importlib.reload(diagnostics.tropical_rainfall.tr_pr_mod)
        from  diagnostics.tropical_rainfall.tr_pr_mod import TR_PR_Diagnostic
        break
    except NameError:
        import diagnostics.tropical_rainfall.tr_pr_mod
        from  diagnostics.tropical_rainfall.tr_pr_mod import TR_PR_Diagnostic
        break

In [185]:
import importlib    
importlib.reload(diagnostics.tropical_rainfall.tr_pr_mod)

from  diagnostics.tropical_rainfall.tr_pr_mod import TR_PR_Diagnostic

In [175]:
""" 
if 'tr_pr_mod' not in sys.modules:
    import diagnostics.tropical_rainfall.tr_pr_mod
    print('import')
else:                      
    import importlib      
    importlib.reload(diagnostics.tropical_rainfall.tr_pr_mod) # reload module on subsequent runs
    print("reload")
    
from  diagnostics.tropical_rainfall.tr_pr_mod import TR_PR_Diagnostic
"""

import


In [12]:
diag = TR_PR_Diagnostic()

diag.num_of_bins = 15
diag.first_edge = 0
diag.width_of_bin = 2000*10**(-6)/diag.num_of_bins

last_edge = diag.first_edge  + diag.num_of_bins*diag.width_of_bin

In [13]:
from aqua import Reader
from aqua.reader import catalogue

In [9]:
catalogue()

IFS	tco3999-ng5	2.8km experiment, coupled with FESOM
	- ICMGG_atm2d	
	- ICMU_atm2d	
	- ICMU_atm3d	
	- interpolated_global	
	- interpolated_np	
	- interpolated_sp	
	- interpolated_sp_ci	
IFS	tco2559-ng5	4km experiment, coupled with FESOM
	- ICMGG_atm2d	
	- ICMU_atm2d	
	- ICMU_atm3d	
	- interpolated_global	
	- interpolated_np	
	- interpolated_sp	
IFS	tco1279-orca025	9km baseline, coupled to NEMO, deep conv ON
	- ICMGG_atm2d	
	- ICMU_atm2d	
	- ICMU_atm3d	

FESOM	tco3999-ng5	2.5km experiment, coupuled with IFS
	- elem_grid	
	- node_grid	
	- np	nearest-neighbor interpolation to lat-lon grid
	- interpolated_global2d	
	- interpolated_global_TS	
	- interpolated_global_UV	
	- interpolated_np	
	- interpolated_sp	
	- original_2d	original 2d output
	- original_3d	original 3d output
FESOM	tco2559-ng5	5km experiment, coupuled with IFS
	- elem_grid	
	- node_grid	
	- interpolated_global2d	
	- interpolated_global_TS	
	- interpolated_global_UV	
	- interpolated_np	
	- interpolated_sp	
	- original_2d	orig

config:
  args:
    path: ./config/catalog.yaml
  description: ''
  driver: intake.catalog.local.YAMLFileCatalog
  metadata: {}


In [14]:
reader = Reader(model="ICON", exp="ngc2009", source="atm_2d_ml_R02B06")#, regrid="r100")
#data = reader.retrieve(fix=False)
#data = reader.retrieve(apply_unit_fix=False)
ICON_2009 = reader.retrieve()

No fixes defined for model  ICON


In [167]:
ICON_2009

<xarray.Dataset>
Dimensions:   (time: 37009, cell: 327680)
Coordinates:
  * time      (time) datetime64[ns] 2020-01-20 ... 2022-03-01
Dimensions without coordinates: cell
Data variables: (12/34)
    cfh_lnd   (time, cell) float32 dask.array<chunksize=(6, 327680), meta=np.ndarray>
    clivi     (time, cell) float32 dask.array<chunksize=(6, 327680), meta=np.ndarray>
    cllvi     (time, cell) float32 dask.array<chunksize=(6, 327680), meta=np.ndarray>
    cptgzvi   (time, cell) float32 dask.array<chunksize=(6, 327680), meta=np.ndarray>
    hfls      (time, cell) float32 dask.array<chunksize=(6, 327680), meta=np.ndarray>
    hfss      (time, cell) float32 dask.array<chunksize=(6, 327680), meta=np.ndarray>
    ...        ...
    tas       (time, cell) float32 dask.array<chunksize=(6, 327680), meta=np.ndarray>
    tauu      (time, cell) float32 dask.array<chunksize=(6, 327680), meta=np.ndarray>
    tauv      (time, cell) float32 dask.array<chunksize=(6, 327680), meta=np.ndarray>
    ts        (time, cell) float32 dask.array<chunksize=(6, 327680), meta=np.ndarray>
    uas       (time, cell) float32 dask.array<chunksize=(6, 327680), meta=np.ndarray>
    vas       (time, cell) float32 dask.array<chunksize=(6, 327680), meta=np.ndarray>
Attributes:
    CDI:                  Climate Data Interface version 1.8.3rc (http://mpim...
    Conventions:          CF-1.6
    comment:              Sapphire Dyamond (k203123) on l40687 (Linux 4.18.0-...
    grid_file_uri:        http://icon-downloads.mpimet.mpg.de/grids/public/mp...
    history:              ./icon at 20220512 152214
    institution:          Max Planck Institute for Meteorology/Deutscher Wett...
    number_of_grid_used:  15
    references:           see MPIM/DWD publications
    source:               git@gitlab.dkrz.de:icon/icon-aes.git@87a1eaded69e87...
    title:                ICON simulation
    uuidOfHGrid:          0ccb7a5e-ab5a-11e8-9938-b7a2f84bd2d4

In [15]:
import xarray as xr 
import matplotlib.pyplot as plt
import numpy as np 

In [16]:
ICON_2009_small = ICON_2009['pr'][0:100,:]
ICON_2009_small = ICON_2009_small.compute()

In [40]:
#diag.time_interpreter_b(ICON_2009)

diag.time_interpreter_b(ICON_2009_small) 

timestep is 30 minutes


'MINUTE'

## Numpy.package (Numpy.digitize + Numpy.count_nonzero)

In [17]:
hist_digitize, size,  del_time_digitize = diag.hist_np_digitize(ICON_2009_small,  preprocess = False)
hist_digitize

<xarray.DataArray (bin: 15)>
array([31195073,   646876,   280131,   160574,   103433,    72720,
          53261,    40553,    31905,    25767,    20959,    17618,
          14783,    12788,    10624])
Coordinates:
  * bin      (bin) float64 0.0 0.0001333 0.0002667 ... 0.0016 0.001733 0.001867

## fast_histogram package (fast_histogram.histogram1d)

In [18]:
hist_fast,  size,   del_time_fast  = diag.hist1d_fast(ICON_2009_small,  preprocess = False)
hist_fast

<xarray.DataArray (bin: 15)>
array([3.1195073e+07, 6.4687600e+05, 2.8013100e+05, 1.6057400e+05,
       1.0343300e+05, 7.2720000e+04, 5.3261000e+04, 4.0553000e+04,
       3.1905000e+04, 2.5767000e+04, 2.0959000e+04, 1.7618000e+04,
       1.4783000e+04, 1.2788000e+04, 1.0624000e+04])
Coordinates:
  * bin      (bin) float64 0.0 0.0001333 0.0002667 ... 0.0016 0.001733 0.001867

## Numpy package (Numpy.histogram)

In [19]:
hist_np,  size, del_time_np = diag.hist1d_np(ICON_2009_small,  preprocess = False)
hist_np

<xarray.DataArray (bin: 15)>
array([31195073,   646876,   280131,   160574,   103433,    72720,
          53261,    40553,    31905,    25767,    20959,    17618,
          14783,    12788,    10624])
Coordinates:
  * bin      (bin) float32 0.0 0.0001333 0.0002667 ... 0.0016 0.001733 0.001867

In [20]:
ICON_2009_small_prep = ICON_2009_small.stack(total=['time', 'cell'])

##  matplotlib.pyplot package (matplotlib.pyplot.hist)

In [21]:
#%%skip True
hist_pyplt,  size, del_time_pyplt = diag.hist1d_pyplot(ICON_2009_small_prep,  preprocess = False)

## Dask packages

In [22]:
import dask.array as da

In [23]:
ICON_2009_small_prep_dask = da.from_array(ICON_2009_small_prep)

## dask_histogram.boost package (dask_histogram.boost.Histogram)

In [24]:
hist_boost, size,  del_time_boost = diag.dask_boost(ICON_2009_small_prep_dask,  preprocess = False)

dask.array<to-dask-array, shape=(15,), dtype=float64, chunksize=(15,), chunktype=numpy.ndarray> [dask.array<array, shape=(16,), dtype=float64, chunksize=(16,), chunktype=numpy.ndarray>]


## dask_histogram package  (dask_histogram.factory)

In [25]:
hist_factory, size,  del_time_factory = diag.dask_factory(ICON_2009_small_prep_dask,  preprocess = False)
hist_factory

<xarray.DataArray (bin: 15)>
array([3.1195073e+07, 6.4687600e+05, 2.8013100e+05, 1.6057400e+05,
       1.0343300e+05, 7.2720000e+04, 5.3261000e+04, 4.0553000e+04,
       3.1905000e+04, 2.5767000e+04, 2.0959000e+04, 1.7618000e+04,
       1.4783000e+04, 1.2788000e+04, 1.0624000e+04])
Coordinates:
  * bin      (bin) float64 0.0 0.0001333 0.0002667 ... 0.0016 0.001733 0.001867

In [ ]:
# Check the scaling 

# lat + lon coordinates

In [ ]:
# check with regrider of prev dataset

In [26]:
CMIP_2010           = xr.open_dataset("/work/bb1153/b382267/data_mafalda/pr_day_EC-Earth3_historical_r1i1p1f1_gr_20100101-20101231.nc")

In [27]:
diag.time_interpreter_b(CMIP_2010 )


timestep is day


'D'

In [28]:
CMIP_2010_trop = diag.ds_per_lat_range(CMIP_2010)['pr'].stack(total=['time', 'lat', 'lon'])

## Numpy.package (Numpy.digitize + Numpy.count_nonzero)

In [29]:
CMIP_hist_digitize, size,  del_time_CMIP_digitize = diag.hist_np_digitize(CMIP_2010_trop,  preprocess = False)
CMIP_hist_digitize

<xarray.DataArray (bin: 15)>
array([4097049,  606786,  128823,   26648,    5860,    1475,     397,
           162,      67,      47,      12,      19,      11,       3,
             5])
Coordinates:
  * bin      (bin) float64 0.0 0.0001333 0.0002667 ... 0.0016 0.001733 0.001867

In [30]:
CMIP_hist_digitize_pr, _size_digitize, del_time_CMIP_digitize_Prepr = diag.hist_np_digitize(CMIP_2010)
CMIP_hist_digitize_pr

<xarray.DataArray (bin: 15)>
array([4097049,  606786,  128823,   26648,    5860,    1475,     397,
           162,      67,      47,      12,      19,      11,       3,
             5])
Coordinates:
  * bin      (bin) float64 0.0 0.0001333 0.0002667 ... 0.0016 0.001733 0.001867

## fast_histogram package (fast_histogram.histogram1d)

In [31]:
CMIP_hist_fast,  _CMIP_trpr_size,   del_time_CMIP_fast  = diag.hist1d_fast(CMIP_2010_trop,  preprocess = False)
CMIP_hist_fast

<xarray.DataArray (bin: 15)>
array([4.097049e+06, 6.067860e+05, 1.288230e+05, 2.664800e+04,
       5.860000e+03, 1.475000e+03, 3.970000e+02, 1.620000e+02,
       6.700000e+01, 4.700000e+01, 1.200000e+01, 1.900000e+01,
       1.100000e+01, 3.000000e+00, 5.000000e+00])
Coordinates:
  * bin      (bin) float64 0.0 0.0001333 0.0002667 ... 0.0016 0.001733 0.001867

In [32]:
CMIP_hist_fast_pr,  _CMIP_trpr_size,   del_time_CMIP_fast  = diag.hist1d_fast(CMIP_2010)
CMIP_hist_fast_pr

<xarray.DataArray (bin: 15)>
array([4.097049e+06, 6.067860e+05, 1.288230e+05, 2.664800e+04,
       5.860000e+03, 1.475000e+03, 3.970000e+02, 1.620000e+02,
       6.700000e+01, 4.700000e+01, 1.200000e+01, 1.900000e+01,
       1.100000e+01, 3.000000e+00, 5.000000e+00])
Coordinates:
  * bin      (bin) float64 0.0 0.0001333 0.0002667 ... 0.0016 0.001733 0.001867

## Numpy package (Numpy.histogram)

In [33]:
CMIP_hist_np,  size, del_time_CMIP_np = diag.hist1d_np(CMIP_2010_trop,  preprocess = False)
CMIP_hist_np

<xarray.DataArray (bin: 15)>
array([4097049,  606786,  128823,   26648,    5860,    1475,     397,
           162,      67,      47,      12,      19,      11,       3,
             5])
Coordinates:
  * bin      (bin) float32 0.0 0.0001333 0.0002667 ... 0.0016 0.001733 0.001867

##  matplotlib.pyplot package (matplotlib.pyplot.hist)

In [34]:
CMIP_hist_pyplt,  s, del_time_CMIP_pyplt = diag.hist1d_pyplot(CMIP_2010_trop,  preprocess = False)


In [35]:
import dask.array as da

In [36]:
CMIP_2010_trop_dask = da.from_array(CMIP_2010_trop)


## dask_histogram package  (dask_histogram.factory)

In [37]:
CMIP_hist_fact, size,  del_time_CMIP_fact = diag.dask_factory(CMIP_2010_trop_dask,  preprocess = False, delay = False)
CMIP_hist_fact

<xarray.DataArray (bin: 15)>
array([4.097049e+06, 6.067860e+05, 1.288230e+05, 2.664800e+04,
       5.860000e+03, 1.475000e+03, 3.970000e+02, 1.620000e+02,
       6.700000e+01, 4.700000e+01, 1.200000e+01, 1.900000e+01,
       1.100000e+01, 3.000000e+00, 5.000000e+00])
Coordinates:
  * bin      (bin) float64 0.0 0.0001333 0.0002667 ... 0.0016 0.001733 0.001867

In [41]:
CMIP_hist_fact_weights, size,  del_time_CMIP_fact_w = diag.dask_factory_weights(CMIP_2010_trop_dask,  preprocess = False, delay = False)


## dask_histogram.boost package (dask_histogram.boost.Histogram)

In [38]:
CMIP_hist_boost, size_CMIP,  del_time_CMIP_boost = diag.dask_boost(CMIP_2010_trop_dask,  preprocess = False)
CMIP_hist_boost


dask.array<to-dask-array, shape=(15,), dtype=float64, chunksize=(15,), chunktype=numpy.ndarray> [dask.array<array, shape=(16,), dtype=float64, chunksize=(16,), chunktype=numpy.ndarray>]


<xarray.DataArray (bin: 15)>
array([4.097049e+06, 6.067860e+05, 1.288230e+05, 2.664800e+04,
       5.860000e+03, 1.475000e+03, 3.970000e+02, 1.620000e+02,
       6.700000e+01, 4.700000e+01, 1.200000e+01, 1.900000e+01,
       1.100000e+01, 3.000000e+00, 5.000000e+00])
Coordinates:
  * bin      (bin) float64 0.0 0.0001333 0.0002667 ... 0.0016 0.001733 0.001867

In [173]:

fig = plt.figure()
ax = fig.add_subplot(111)

_pdf = True

diag.hist_plot(hist_boost,          pdf=_pdf,   color = 'tab:purple',  label='right')
diag.hist_plot(hist_factory,        pdf=_pdf,   color = 'tab:grey',    label='left')
diag.hist_plot(hist_fast,           pdf=_pdf,   color = 'tab:red',     label='fast')
diag.hist_plot(hist_np,             pdf=_pdf,   color = 'tab:green',   label='np')
diag.hist_plot(hist_pyplt,          pdf=_pdf,   color = 'tab:blue',    label='pyplt')
diag.hist_plot(hist_digitize,       pdf=_pdf,   color = 'tab:blue',    label='pyplt')



ax.grid()

plt.savefig("./figures/pdf_hists_2.png",
            bbox_inches ="tight",
            pad_inches = 1,
            transparent = True,
            facecolor ="w",
            edgecolor ='w',
            orientation ='landscape')

hist_plot function in the process 

hist_plot function in the process 

hist_plot function in the process 

hist_plot function in the process 

hist_plot function in the process 

hist_plot function in the process 



In [189]:

fig = plt.figure()
ax = fig.add_subplot(111)

_pdf = True

diag.hist_plot(CMIP_hist_boost,     pdf=_pdf,   color = 'tab:purple',  label='right')
diag.hist_plot(CMIP_hist_fact,      pdf=_pdf,   color = 'tab:grey',    label='left')
diag.hist_plot(CMIP_hist_fast,      pdf=_pdf,   color = 'tab:red',     label='fast')
diag.hist_plot(CMIP_hist_np,        pdf=_pdf,   color = 'tab:green',   label='np')
diag.hist_plot(CMIP_hist_pyplt,     pdf=_pdf,   color = 'tab:blue',    label='pyplt')
diag.hist_plot(CMIP_hist_digitize,  pdf=_pdf,   color = 'tab:blue',    label='pyplt')



ax.grid()

plt.savefig("./figures/pdf_hists.png",
            bbox_inches ="tight",
            pad_inches = 1,
            transparent = True,
            facecolor ="w",
            edgecolor ='w',
            orientation ='landscape')



hist_plot function in the process 

pdf
hist_plot function in the process 

pdf
hist_plot function in the process 

pdf
hist_plot function in the process 

pdf
hist_plot function in the process 

pdf
hist_plot function in the process 

pdf


In [ ]:
# timeit 

In [39]:
time_set1 = [ del_time_CMIP_boost, del_time_CMIP_fact,  del_time_CMIP_fast,  del_time_CMIP_np, del_time_CMIP_pyplt,  del_time_CMIP_digitize ]

time_set2 = [ del_time_boost, del_time_factory,  del_time_fast,  del_time_np, del_time_pyplt,  del_time_digitize ]

Per_element = True

if Per_element == True:
    time_set1 = [time_set1[i]/size_CMIP for i in range(len(time_set1))] 

if Per_element == True:
    time_set2 = [time_set2[i]/size for i in range(len(time_set2))] 

fig = plt.figure(figsize=(12,6))

barWidth = 0.2
br1 = np.arange(len(time_set1))
br2 = [x + barWidth for x in br1]

plt.bar(br1, time_set1, color ='red',  width = barWidth,
        edgecolor ='grey', label = "ICON") #'aqua, 3.10.9')

plt.bar(br2, time_set2, color ='green',  width = barWidth,
        edgecolor ='grey', label = "CMIP") #'aqua, 3.10.9')
#plt.bar(br1, time_set1_3_9_16, color ='red', alpha =0.6, width = barWidth, bottom = time_set1_3_8_16,
#        edgecolor ='grey', label ='CMIP, 3.9.16')
 
# Adding Xticks
plt.xlabel('Methods', fontweight ='bold', fontsize = 15)
plt.ylabel('Calculation time per element', fontweight ='bold', fontsize = 15)
plt.xticks([r + barWidth for r in range(len(time_set1))],
        ['boost', 'factory', 'fast', 'np', 'pyplt', 'digitize'], fontsize=14)  #, 'left'
plt.xticks(fontsize=14)         



plt.legend(fontsize=14)


plt.savefig("./figures/Calc_time_diffver.png",
            bbox_inches ="tight",
            pad_inches = 1,
            transparent = True,
            facecolor ="w",
            edgecolor ='w',
            orientation ='landscape')


