In [4]:

from dask_jobqueue import SLURMCluster # pip 
from dask.distributed import Client, progress 
import dask


import matplotlib as mpl
# Define Agg as Backend for matplotlib when no X server is running
mpl.use('Agg')
import socket
import os

In [5]:

def squeue_user(username = "$USER"):
    _squeue_user = os.system("squeue --user="+str(username))
    return _squeue_user 

with os.popen("pwd ") as f:
    _pwd = f.readline()

In [3]:
cluster = SLURMCluster(
    name='dask-cluster', 
    cores=256,    
    memory="500 GB", 
    project="bb1153",
    queue= "compute", 
    #interface='ib0',
    walltime='04:30:50',
)
client = Client(cluster)
print(cluster.job_script())

/home/b/b382267/mambaforge/envs/aqua/lib/python3.10/site-packages/dask_jobqueue/slurm.py:49: FutureWarning: project has been renamed to account as this kwarg was used wit -A option. You are still using it (please also check config files). If you did not set account yet, project will be respected for now, but it will be removed in a future release. If you already set account, project is ignored and you can remove it.
  warnings.warn(warn, FutureWarning)


#!/usr/bin/env bash

#SBATCH -J dask-worker
#SBATCH -p compute
#SBATCH -A bb1153
#SBATCH -n 1
#SBATCH --cpus-per-task=256
#SBATCH --mem=466G
#SBATCH -t 04:30:50

/home/b/b382267/mambaforge/envs/aqua/bin/python -m distributed.cli.dask_worker tcp://136.172.124.3:38501 --nthreads 16 --nworkers 16 --memory-limit 29.10GiB --name dummy-name --nanny --death-timeout 60



/home/b/b382267/mambaforge/envs/aqua/lib/python3.10/site-packages/dask_jobqueue/slurm.py:49: FutureWarning: project has been renamed to account as this kwarg was used wit -A option. You are still using it (please also check config files). If you did not set account yet, project will be respected for now, but it will be removed in a future release. If you already set account, project is ignored and you can remove it.
  warnings.warn(warn, FutureWarning)


In [4]:
cluster.scale(jobs=1)

In [6]:
squeue_user()

             JOBID PARTITION     NAME     USER ST       TIME  NODES NODELIST(REASON)
           4160211   compute dask-wor  b382267  R      32:04      1 l40065


0

In [7]:


import sys
if 'tr_pr_mod' not in sys.modules:
    import diagnostics.tropical_rainfall.tr_pr_mod
else:                      
    import importlib      
    importlib.reload(diagnostics.tropical_rainfall.tr_pr_mod) # reload module on subsequent runs
    
from  diagnostics.tropical_rainfall.tr_pr_mod import TR_PR_Diagnostic




In [29]:
diag = TR_PR_Diagnostic()

diag.num_of_bins = 15
diag.first_edge = 0
diag.width_of_bin = 2000*10**(-6)/diag.num_of_bins

last_edge = diag.first_edge  + diag.num_of_bins*diag.width_of_bin

In [8]:
from aqua import Reader
from aqua.reader import catalogue

In [9]:
catalogue()

IFS	tco3999-ng5	2.8km experiment, coupled with FESOM
	- ICMGG_atm2d	
	- ICMU_atm2d	
	- ICMU_atm3d	
	- interpolated_global	
	- interpolated_np	
	- interpolated_sp	
	- interpolated_sp_ci	
IFS	tco2559-ng5	4km experiment, coupled with FESOM
	- ICMGG_atm2d	
	- ICMU_atm2d	
	- ICMU_atm3d	
	- interpolated_global	
	- interpolated_np	
	- interpolated_sp	
IFS	tco1279-orca025	9km baseline, coupled to NEMO, deep conv ON
	- ICMGG_atm2d	
	- ICMU_atm2d	
	- ICMU_atm3d	

FESOM	tco3999-ng5	2.5km experiment, coupuled with IFS
	- elem_grid	
	- node_grid	
	- np	nearest-neighbor interpolation to lat-lon grid
	- interpolated_global2d	
	- interpolated_global_TS	
	- interpolated_global_UV	
	- interpolated_np	
	- interpolated_sp	
	- original_2d	original 2d output
	- original_3d	original 3d output
FESOM	tco2559-ng5	5km experiment, coupuled with IFS
	- elem_grid	
	- node_grid	
	- interpolated_global2d	
	- interpolated_global_TS	
	- interpolated_global_UV	
	- interpolated_np	
	- interpolated_sp	
	- original_2d	orig

config:
  args:
    path: ./config/catalog.yaml
  description: ''
  driver: intake.catalog.local.YAMLFileCatalog
  metadata: {}


In [10]:
reader = Reader(model="ICON", exp="ngc2009", source="atm_2d_ml_R02B06")
#data = reader.retrieve(fix=False)
#data = reader.retrieve(apply_unit_fix=False)
ICON_2009 = reader.retrieve()

No fixes defined for model  ICON


In [11]:
ICON_2009

<xarray.Dataset>
Dimensions:   (time: 37009, cell: 327680)
Coordinates:
  * time      (time) datetime64[ns] 2020-01-20 ... 2022-03-01
Dimensions without coordinates: cell
Data variables: (12/34)
    cfh_lnd   (time, cell) float32 dask.array<chunksize=(6, 327680), meta=np.ndarray>
    clivi     (time, cell) float32 dask.array<chunksize=(6, 327680), meta=np.ndarray>
    cllvi     (time, cell) float32 dask.array<chunksize=(6, 327680), meta=np.ndarray>
    cptgzvi   (time, cell) float32 dask.array<chunksize=(6, 327680), meta=np.ndarray>
    hfls      (time, cell) float32 dask.array<chunksize=(6, 327680), meta=np.ndarray>
    hfss      (time, cell) float32 dask.array<chunksize=(6, 327680), meta=np.ndarray>
    ...        ...
    tas       (time, cell) float32 dask.array<chunksize=(6, 327680), meta=np.ndarray>
    tauu      (time, cell) float32 dask.array<chunksize=(6, 327680), meta=np.ndarray>
    tauv      (time, cell) float32 dask.array<chunksize=(6, 327680), meta=np.ndarray>
    ts        (time, cell) float32 dask.array<chunksize=(6, 327680), meta=np.ndarray>
    uas       (time, cell) float32 dask.array<chunksize=(6, 327680), meta=np.ndarray>
    vas       (time, cell) float32 dask.array<chunksize=(6, 327680), meta=np.ndarray>
Attributes:
    CDI:                  Climate Data Interface version 1.8.3rc (http://mpim...
    Conventions:          CF-1.6
    comment:              Sapphire Dyamond (k203123) on l40687 (Linux 4.18.0-...
    grid_file_uri:        http://icon-downloads.mpimet.mpg.de/grids/public/mp...
    history:              ./icon at 20220512 152214
    institution:          Max Planck Institute for Meteorology/Deutscher Wett...
    number_of_grid_used:  15
    references:           see MPIM/DWD publications
    source:               git@gitlab.dkrz.de:icon/icon-aes.git@87a1eaded69e87...
    title:                ICON simulation
    uuidOfHGrid:          0ccb7a5e-ab5a-11e8-9938-b7a2f84bd2d4

In [24]:
import xarray as xr 
import matplotlib.pyplot as plt
import numpy as np 

In [17]:
ICON_2009_small = ICON_2009['pr'][0:10,:]
ICON_2009_small = ICON_2009_small.compute()

In [19]:
diag.time_interpreter_b(ICON_2009)

diag.time_interpreter_b(ICON_2009_small) 

timestep is NOT uniform or unknown
old timestep is month


'M'

In [31]:
hist_digitize, size,  del_time_digitize = diag.hist_np_digitize(ICON_2009_small,  preprocess = False)
hist_digitize

<xarray.DataArray (bin: 15)>
array([3205685,   29996,   13361,    7579,    4393,    3028,    2298,
          1604,    1266,     980,     819,     680,     553,     506,
           459])
Coordinates:
  * bin      (bin) float64 0.0 0.0001333 0.0002667 ... 0.0016 0.001733 0.001867

In [33]:
hist_fast,  size,   del_time_fast  = diag.hist1d_fast(ICON_2009_small,  preprocess = False)
hist_fast

<xarray.DataArray (bin: 15)>
array([3.205685e+06, 2.999600e+04, 1.336100e+04, 7.579000e+03,
       4.393000e+03, 3.028000e+03, 2.298000e+03, 1.604000e+03,
       1.266000e+03, 9.800000e+02, 8.190000e+02, 6.800000e+02,
       5.530000e+02, 5.060000e+02, 4.590000e+02])
Coordinates:
  * bin      (bin) float64 0.0 0.0001333 0.0002667 ... 0.0016 0.001733 0.001867

In [39]:
hist_np,  size, del_time_np = diag.hist1d_np(ICON_2009_small,  preprocess = False)
hist_np

<xarray.DataArray (bin: 15)>
array([3205685,   29996,   13361,    7579,    4393,    3028,    2298,
          1604,    1266,     980,     819,     680,     553,     506,
           459])
Coordinates:
  * bin      (bin) float32 0.0 0.0001333 0.0002667 ... 0.0016 0.001733 0.001867

In [36]:
#hist_pyplt,  size, del_time_pyplt = diag.hist1d_pyplot(ICON_2009_small,  preprocess = False)

## Dask (doesnt work with NO regrided data now...)

In [37]:
import dask.array as da

In [38]:
ICON_2009_small_dask = da.from_array(ICON_2009_small)

In [ ]:
hist_boost, size,  del_time_boost = diag.dask_boost(ICON_2009_small_dask,  preprocess = False)

In [ ]:
hist_factory, size,  del_time_factory = diag.dask_factory(ICON_2009_small_dask,  preprocess = False)
hist_factory

In [ ]:
"""
fig = plt.figure()
ax = fig.add_subplot(111)

diag.hist_plot(_CMIP_hist_right,    pdf=True,   _color = 'tab:purple',  _label='right')
diag.hist_plot(_CMIP_hist_left,     pdf=True,   _color = 'tab:grey',    _label='left')
diag.hist_plot(_CMIP_hist_fast,     pdf=True,   _color = 'tab:red',     _label='fast')
diag.hist_plot(_CMIP_hist_np,       pdf=True,   _color = 'tab:green',   _label='np')
diag.hist_plot(_CMIP_hist_pyplt,    pdf=True,   _color = 'tab:blue',    _label='pyplt')


diag.hist_plot(_BCC_hist_right,     pdf=True,   _ls ='--', _color = 'tab:purple')
diag.hist_plot(_BCC_hist_left,      pdf=True,   _ls ='--', _color = 'tab:grey')
diag.hist_plot(_BCC_hist_fast,      pdf=True,   _ls ='--', _color = 'tab:red')
diag.hist_plot(_BCC_hist_np,        pdf=True,   _ls ='--', _color = 'tab:green')
diag.hist_plot(_BCC_hist_pyplt,     pdf=True,   _ls ='--', _color = 'tab:blue')


ax2 = ax.twinx()
ax2.plot([None, None], '-', label = 'CMIP')
ax2.plot([None, None],  '--', label = 'BCC')
ax2.legend(fontsize=14)
ax.legend(loc = 'lower left', fontsize=14)
ax.grid()

plt.savefig("./figures/pdf_trop_pr_3_9_16.png",
            bbox_inches ="tight",
            pad_inches = 1,
            transparent = True,
            facecolor ="w",
            edgecolor ='w',
            orientation ='landscape')

"""


In [ ]:
""" 
if Per_element == True:
    _.. = [time_set1/size for i in range(len(time_set1))] 
    .. = [time_set2[i]/size for i in range(len(time_set2))] 

fig = plt.figure(figsize=(12,6))

barWidth = 0.2
br1 = np.arange(len(time_set1))
br2 = [x + barWidth for x in br1]

plt.bar(br1, time_set1_3_8_16, color ='red',  width = barWidth
        edgecolor ='grey', label ='CMIP, 3.8.16')
p1 = plt.bar(br2, time_set2_3_8_16, color ='green', width = barWidth, 
        edgecolor ='grey', label ='BCC, 3.8.16')

plt.bar(br1, time_set1_3_9_16, color ='red', alpha =0.6, width = barWidth, bottom = time_set1_3_8_16,
        edgecolor ='grey', label ='CMIP, 3.9.16')
p1 = plt.bar(br2, time_set1_3_9_16, color ='green', alpha =0.6, width = barWidth, bottom = time_set1_3_8_16, 
        edgecolor ='grey', label ='BCC, 3.9.16')

_bottom = [_time_CMIP_3_8_16[i] +_time_CMIP_3_9_16[i] for i in range(0, len(_time_CMIP_3_8_16))]
plt.bar(br1, _time_CMIP_3_11_0, color ='tab:red', alpha =0.4,  width = barWidth, bottom = _bottom,
        edgecolor ='grey', label ='CMIP, 3.11.0')
_bottom = [_time_BCC_3_8_16[i] +_time_BCC_3_9_16[i] for i in range(0, len(_time_BCC_3_8_16))]
p2 = plt.bar(br2, _time_BCC_3_11_0, color ='tab:green',  alpha =0.4,  width = barWidth, bottom = _bottom,
        edgecolor ='grey', label ='BCC, 3.11.0')


 
# Adding Xticks
plt.xlabel('Methods', fontweight ='bold', fontsize = 15)
plt.ylabel('Calculation time per element', fontweight ='bold', fontsize = 15)
plt.xticks([r + barWidth for r in range(len(_time_CMIP))],
        ['np', 'fast', 'loopr', 'digitize' AND ETC], fontsize=14)  #, 'left'
plt.xticks(fontsize=14)         



plt.legend(fontsize=14)


plt.savefig("./figures/Calc_time_diffver.png",
            bbox_inches ="tight",
            pad_inches = 1,
            transparent = True,
            facecolor ="w",
            edgecolor ='w',
            orientation ='landscape')


"""